global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'apigateway'
    static_configs:
      - targets: ['apigateway:8080']
  
  - job_name: 'userservice'
    static_configs:
      - targets: ['userservice:8080']
  
  - job_name: 'orderservice'
    static_configs:
      - targets: ['orderservice:8080']
  
  - job_name: 'productservice'
    static_configs:
      - targets: ['productservice:8080']


